### ISSUE TITLE
Request to upload header file

### ISSUE THREAD

**Issue by byt-notes** [weiseng18/nus-cheatsheets#1]
Hi, I found the CS1231S cheatsheet is very useful, and I like the template you used. But, I would like to make some changes, could you please include the header file that you have used? Thank you.   

This is what I mean by "header file":
```
\input{"../headers/cheat_sheet.tex"}
\input{"../headers/sets.tex"}
```

**Comment by byt-notes** [comment]
Sorry, I just saw the header folder in the repo.

**Comment by weiseng18** [comment]
By the way, I've found the header file format not so ideal as many files might depend on the same file and it might be hard to manage changes. So for Y2S1 onwards I'm avoiding header files where possible 🙂
